---
title: "ANA 515 Assignment 2"
author: Karthikeyan Rajendran
date: 2021
output: 
html_document:
  theme:
    bootswatch: Darkly
---


```{r setup, include = FALSE}

library(ggplot2)
library(dplyr)
library(tidyverse)
library(knitr)
```

```{r, include = TRUE}
#The data has 13 different drug across 17 different age groups. It is about the drug usage across different age groups. This data is collected from the 'National survey on drug use and health from the substance abuse and mental health data archive'.The data is stored as .csv file and it has 18 lines containing age groups and drug usage. From this data we can find out which drug is mostly used and/or which age groups moslty use the drug. The data set has the information of age and drug usage of last 12 months.  
```

```{r, include = TRUE}
location <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/drug-use-by-age/drug-use-by-age.csv"
druguse <- read.csv(location)
# read.csv() R function is being used to read the data. It comes from R utils package which is installed by default.
```

```{r, include = TRUE}
colnames(druguse)
r1<-rename(druguse,alcohol_use = alcohol.use)
r2<-rename(r1,marijuana_use = marijuana.use)
r3<-rename(r2,cocaine_use = cocaine.use)
r4<-rename(r3,crack_use = crack.use)
r5<-rename(r4,heroin_use = heroin.use)
r6<-rename(r5,hallucinogen_use = hallucinogen.use)
r7<-rename(r6,inhalant_use = inhalant.use)
r8<-rename(r7,pain_releiver_use = pain.releiver.use)
r9<-rename(r8,oxycontin_use = oxycontin.use)
r10<-rename(r9,tranquilizer_use = tranquilizer.use)
r11<-rename(r10,stimulant_use = stimulant.use)
r12<-rename(r11,meth_use = meth.use)
r13<-rename(r12,sedative_use = sedative.use)
colnames(r13)
```

This dataframe has `r nrow(r13)` rows and `r ncol(r13)` columns. The names of the columns and a brief description of each are in the table below:

```{r, include = TRUE}
tab <- matrix(c("alcohol_use","Percentage of alcohol use", "marijuana_use","Percentage of marijuana use","cocaine_use","Percentage of cocaine use","heroin_use","Percentage of heroin use","hallucinogen_use","Percentage of hallucinogen use","inhalant_use","Percentage of inhalant use","pain_releiver_use","Percentage of pain reliever use","oxycontin_use","Percentage of oxycontin use","tranquilizer_use","Percentage of tranquilizer use","stimulant_use","Percentage of stimulant use","meth_use","Percentage of meth use","sedative_use","Percentage of sedative use"), ncol = 2, byrow=TRUE)
colnames(tab) <- c('column name','description')
tab <- as.table(tab)
tab
```


```{r, include = TRUE}
druguse_sub <- subset(r13, select = c(alcohol_use, crack_use, cocaine_use))
druguse_summ<-summary(druguse_sub)
druguse_summ
```







